---

- name: mkdir resource directory
  file: path="{{ role_path }}/{{ rcpath}}" state=directory

# Prepare sshkeys
- name: check if sshkeys exist
  stat: path="{{ role_path }}/{{ rcpath}}/sshkeys"
  register: sskeystat
- name: mkdir sshkeys directory
  file: path="{{ role_path }}/{{ rcpath}}/sshkeys" state=directory
- name: generate ssh keys
  shell: ssh-keygen -t rsa -P '' -f {{ role_path }}/{{ rcpath}}/sshkeys/{{ item}}_rsa -C {{ item }}@hadoop-cluster
  with_items:
    - hadoop
    - hdfs
    - yarn
    - mapred
  when: sskeystat.stat.isdir is not defined
