---

- name: mkdir resource directory
  file: path="{{ role_path }}/{{ rcpath}}" state=directory

# Prepare hadoop resource
- name: check hadoop_tar_file exists
  stat: path="{{ role_path }}/{{ rcpath}}/{{ hadoop_conf.tar_file }}"
  register: tar_stat
- name: download hadoop
  get_url: url="{{ hadoop_conf.download_url }}"
    dest="{{ role_path }}/{{ rcpath}}/{{ hadoop_conf.tar_file }}"
    checksum="{{ hadoop_conf.download_checksum_sha256 }}"
  when: not tar_stat.stat.exists

# Prepare sshkeys
- name: check if sshkeys exist
  stat: path="{{ role_path }}/{{ rcpath}}/sshkeys"
  register: sskeystat
- name: mkdir sshkeys directory
  file: path="{{ role_path }}/{{ rcpath}}/sshkeys" state=directory
- name: generate ssh keys
  shell: ssh-keygen -t rsa -P '' -f {{ role_path }}/{{ rcpath}}/sshkeys/{{ item}}_rsa -C {{ item }}@hadoop-cluster
  with_items:
    - hadoop
    - hdfs
    - yarn
    - mapred
  when: sskeystat.stat.isdir is not defined
