---

- setup:

- name: os dependened vars
  include_vars: '{{ item }}'
  with_first_found:
  - files:
      - '{{ ansible_os_family }}.yml'
      - 'default.yml'
    paths: '{{ role_path }}/vars/os'

- include_vars: 
    file: '{{ playbook_dir }}/conf/hosts.yml'
    name: cluster_nodes
- name: include deploy vars
  include_vars: 
    file: "{{ playbook_dir}}/conf/{{ cluster_mode | ternary('hadoop_cluster_vars.yml','hadoop_standalone_vars.yml') }}"
    name: hadoop_vars
- set_fact: is_namenode=true is_resource_mgr=true
  when: not cluster_mode

- name: Install the dependence packages
  package: name="{{ item }}" state=present
  with_items: '{{ hadoop_dependency }}'

- include: config_hosts.yml
- include: install_hadoop.yml
- include: config_firewall.yml
- include: config_daemons.yml
- include: launch_daemons.yml
