---

- name: Prepare
  hosts: local
  vars:
    init: true
  roles:
    - jdk
    - hadoop
    - spark
    - mesos

- name: Install standalone hadoop
  hosts: hadoop_alone
  become: yes
  become_method: sudo
  vars:
    cluster_mode: false
    fresh_unzip: false
    drop_data: true
  roles:
    - system
    - jdk
    - hadoop
    - spark
    - mesos

- name: Install hadoop cluster
  hosts: hadoop_cluster
  become: yes
  become_method: sudo
  vars:
    cluster_mode: true
    fresh_unzip: false
    drop_data: true
  roles: 
    - system
    - common
    - hosts
    - jdk
    - hadoop
    - spark
    - mesos
