---


- debug: msg="will set hostname as {{ hostname }}"

- hostname: name="{{ hostname }}"

- include_vars: 
    file: '{{ playbook_dir }}/conf/hosts.yml'
    name: _temp_hosts
- set_fact:
    hosts_map: "{{ _temp_hosts.hosts }}"
    hosts_list: "{{ _temp_hosts.hosts | list | map('extract', _temp_hosts.hosts) | list}}"
- set_fact:
    hosts: "{{ hosts_list }}"
    slaves: "{{ groups['hdfs_slaves'] }}"

# - debug: msg="{{ hosts_map[item].hostname }}"
#   with_items: "{{ slaves }}"

# Configure /etc/hosts
- name: update /etc/hosts {{ ":" }} drop 127.0.0.1 to hostname (avoid address binding problem)
  lineinfile:
    dest: /etc/hosts
    regexp: '^(127\.0\.0\.1)(.*?)({{ hostname }})$'
    line: '\1\2'
    backrefs: yes

- name: update /etc/hosts {{ ":" }} add hostnames
  lineinfile:
    dest: /etc/hosts
    # regexp: '^({{ item.ip }})?(.*?)(\s)?({{ item.hostname }})?'
    # line: '{{ item.ip }}\2 {{ item.hostname }}'
    # backrefs: yes
    regexp: '^{{ item.address }}(\s)*({{ item.hostname }})?$'
    line: '{{ item.address }} {{ item.hostname }}'
  with_items: "{{ hosts }} "
