---

- name: ssh-keyscan {{ ":" }} 0.0.0.0
  shell: ssh-keyscan -t rsa 0.0.0.0
  changed_when: false
  register: keyscan_0_0_0_0
- name: ssh-keyscan {{ ":" }} localhost
  shell: ssh-keyscan -t rsa localhost
  changed_when: false
  register: keyscan_localhost
- name: edit known_hosts {{ ":" }} add 0.0.0.0 to
  lineinfile: 
    dest=/home/{{ hadoop_user }}/.ssh/known_hosts
    create=yes
    state=present
    line="{{ keyscan_0_0_0_0.stdout }}"
    regexp="^0.0.0.0"
    owner={{ hadoop_user }}
    group={{ hadoop_group }}
- name: edit known_hosts {{ ":" }} add localhost
  lineinfile: 
    dest=/home/{{ hadoop_user }}/.ssh/known_hosts
    create=yes
    state=present
    line="{{ keyscan_localhost.stdout }}"
    regexp="^localhost"
    owner={{ hadoop_user }}
    group={{ hadoop_group }}
