---

- name: prepare known_hosts entry 0.0.0.0
  shell: ssh-keyscan -t rsa 0.0.0.0
  register: keyscan_0_0_0_0

- name: add 0.0.0.0 to known_hosts
  lineinfile: 
    dest=/home/{{ hadoop_user }}/.ssh/known_hosts
    create=yes
    state=present
    line="{{ keyscan_0_0_0_0.stdout }}"
    regexp="^0.0.0.0"
    owner={{ hadoop_user }}
    group={{ hadoop_group }}

- name: prepare known_hosts localhost
  shell: ssh-keyscan -t rsa localhost
  register: keyscan_localhost

- name: add localhost to known_hosts
  lineinfile: 
    dest=/home/{{ hadoop_user }}/.ssh/known_hosts
    create=yes
    state=present
    line="{{ keyscan_localhost.stdout }}"
    regexp="^localhost"
    owner={{ hadoop_user }}
    group={{ hadoop_group }}
