---

- setup:

- include_vars: file='../../../vars/resources.yml'
- include_vars: '{{ item }}'
  with_first_found:
  - files:
      - '{{ ansible_os_family }}.yml'
      - 'default.yml'
    paths: '../vars/os'

- include: install_hadoop.yml

- name: Install the dependence packages
  package:
    name: "{{ item }}"
    state: present
  with_items: '{{ hadoop_dependency }}'
  # when: ansible_os_family == "Debian"

- group: name={{ hadoop_group }} state=present
- user: name={{ hadoop_user }} comment="Hadoop" group={{ hadoop_group }} shell=/bin/bash password=hadoop
- authorized_key: user={{ hadoop_user }} key="{{ lookup('file', '../files/sshkeys/hadoop_rsa.pub') }}"

- include: config_daemons.yml
