---

pkg_ic:
  name: jdk
  repo_install: false
  install_path: /usr/lib/jdk
  url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
  file: jdk-8u131-linux-x64.tar.gz
  basename: jdk1.8.0_131
  # install_dir: /usr/lib/jdk
  # url: http://download.oracle.com/
  # tar_file: jdk-8u144-linux-x64.tar.gz
  # basename: jdk1.8.0_144
