---

host_default_vars:
  ansible_user: swift
  ansible_become_user: root
  ansible_become_pass: passw0rd

hosts:
  node_alone:
    hostname: cluster-node-alone
    address: 192.168.100.105
    vars: {}
  node_000:
    hostname: cluster-node-000
    address: 192.168.100.100
  node_001:
    hostname: cluster-node-001
    address: 192.168.100.101
  node_002:
    hostname: cluster-node-002
    address: 192.168.100.102
  node_003:
    hostname: cluster-node-003
    address: 192.168.100.103
  node_004:
    hostname: cluster-node-004
    address: 192.168.100.104
