---


- include_vars: '{{ item }}'
  with_first_found:
  - files:
      - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
      - '{{ ansible_distribution }}.yml'
      - '{{ ansible_os_family }}.yml'
      - 'default{{ python_suffix }}.yml'
      - 'default.yml'
    paths: '{{ role_path }}/vars/os'
- set_fact:
    mesos_path: '{{ mesos_res.install_dir }}/{{ mesos_res.basename}}'

# install spark files
- name: mkdir mesos
  file: path="{{ mesos_res.install_dir }}" state=directory
- name: upload mesos tar file
  copy:
    src: "{{ role_path }}/{{ rcpath }}/{{ mesos_res.tar_file }}"
    dest: "{{ mesos_res.install_dir }}/{{ mesos_res.tar_file }}"
- name: check unarchive mesos directory
  stat: path="{{ mesos_path }}"
  register: mesosfstat
- name: unarchive mesos
  unarchive:
    src: "{{ mesos_res.install_dir }}/{{ mesos_res.tar_file }}"
    dest: "{{ mesos_res.install_dir }}"
    remote_src: True
  when: mesosfstat.stat.isdir is not defined


# ssh setting
- name: Install the dependence packages
  package: name="{{ item }}" state=present
  with_items: '{{ dependencies }}'
