---


- include_vars: '{{ item }}'
  with_first_found:
  - files:
      - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
      - '{{ ansible_distribution }}.yml'
      - '{{ ansible_os_family }}.yml'
      - 'default{{ python_suffix }}.yml'
      - 'default.yml'
    paths: '{{ role_path }}/vars/os'
- set_fact:
    mesos_path: '{{ mesos_res.install_dir }}/{{ mesos_res.basename}}'

- name: download and unzip
  include_role:
    name: basic/download_and_unzip
  vars:
    pkg_conf: '{{ pkg_ic }}'

# ssh setting
- name: Install the dependence packages
  package: name="{{ item }}" state=present
  with_items: '{{ dependencies }}'

# # make install
# - name: make install
#   shell: |
#     mkdir build
#     cd build
#     ../configure
#     make
#   args:
#     chdir: "{{ pkg_ic.install_path }}/{{ pkg_ic.basename}}"

# - name: check python installation
#   shell: "{{ python_x}} --version 2>&1"
#   register: python_v
#   changed_when: False
#   failed_when: "( python_v | failed ) or ( python_v_expect not in python_v.stdout )"

