---

- name: mkdir resource directory
  file: path="{{ role_path }}/{{ rcpath}}" state=directory

# Prepare spark resource
- set_fact:
    spark_res: "{{ spark_conf.no_hadoop }}"
- name: check tar_file exists
  stat: path="{{ role_path }}/{{ rcpath}}/{{ spark_res.tar_file }}"
  register: tar_stat
- name: download spark
  get_url: url="{{ spark_res.url }}" dest="{{ role_path }}/{{ rcpath}}/{{ spark_res.tar_file }}"
  when: not tar_stat.stat.exists

- set_fact:
    spark_res: "{{ spark_conf.with_hadoop }}"
- name: check tar_file exists
  stat: path="{{ role_path }}/{{ rcpath}}/{{ spark_res.tar_file }}"
  register: tar_stat
- name: download spark
  get_url: url="{{ spark_res.url }}" dest="{{ role_path }}/{{ rcpath}}/{{ spark_res.tar_file }}"
  when: not tar_stat.stat.exists

