---

- setup:

- include_vars: file='../../../vars/resources.yml'
- include_vars: '{{ item }}'
  with_first_found:
  - files:
      - '{{ ansible_os_family }}.yml'
      - 'default.yml'
    paths: '../vars/os'

- include_vars: 
    file: '{{ playbook_dir }}/cluster_nodes.yml'
    name: cluster_nodes
- include_vars: 
    file: '{{ playbook_dir }}/cluster_vars.yml'
    name: cluster_vars

- name: Install the dependence packages
  package: name="{{ item }}" state=present
  with_items: '{{ hadoop_dependency }}'

- include: config_hosts.yml
- include: install_hadoop.yml
- include: config_daemons.yml
- include: launch_daemons.yml
