---

- setup:

- include_vars: file='../../../vars/resources.yml'
- include_vars: '{{ item }}'
  with_first_found:
  - files:
      - '{{ ansible_os_family }}.yml'
      - 'default.yml'
    paths: '../vars/os'

- name: Install the dependence packages
  package: name="{{ item }}" state=present
  with_items: '{{ hadoop_dependency }}'

- group: name={{ hadoop_group }} state=present
- user: name={{ item }} comment={{ item}} group={{ hadoop_group }} shell=/bin/bash password=hadoop
  with_items: "{{ hadoop_users }}"
- authorized_key: user={{ item }} key="{{ lookup('file', '{{ playbook_dir }}/roles/local_prepare/sshkeys/{{ item }}_rsa.pub') }}"
  with_items: "{{ hadoop_users }}"

- include: config_hosts.yml
- include: install_hadoop.yml
- include: config_daemons.yml
- include: launch_daemons.yml
