---

- name: mkdir resource directory
  file: path="{{ role_path }}/{{ rcpath}}" state=directory

# Prepare JDK resource
- name: check tar_file exists
  stat: path="{{ role_path }}/{{ rcpath}}/{{ jdk_conf.tar_file }}"
  register: tar_stat
- name: download jdk
  get_url: url="{{ jdk_conf.download_url }}" dest="{{ role_path }}/{{ rcpath}}/{{ jdk_conf.tar_file }}"
  when: not tar_stat.stat.exists
