---

# install jdk files
- name: mkdir for jdk
  file: path="{{ jdk_conf.install_dir }}" state=directory
- name: upload jdk tar file
  copy:
    src: "{{ rcpath}}/{{ jdk_conf.tar_file }}"
    dest: "{{ jdk_conf.install_dir }}/{{ jdk_conf.tar_file }}"
- name: check unarchive jdk directory
  stat: path="{{ jdk_conf.install_dir }}/{{ jdk_conf.basename }}"
  register: jdkfstat
- name: unarchive jdk
  unarchive:
    src: "{{ jdk_conf.install_dir }}/{{ jdk_conf.tar_file }}"
    dest: "{{ jdk_conf.install_dir }}"
    remote_src: yes
  when: jdkfstat.stat.isdir is not defined

# export environment variable
- name: export JAVA_HOME (/etc/environment)
  lineinfile:
    path: /etc/environment
    regexp: '^JAVA_HOME='
    line: 'JAVA_HOME={{ jdk_conf.install_dir }}/{{ jdk_conf.basename }}'
- name: export JAVA_HOME
  lineinfile:
    path: "{{ sys_profile }}"
    regexp: '^export JAVA_HOME='
    line: 'export JAVA_HOME={{ jdk_conf.install_dir }}/{{ jdk_conf.basename }}'
- name: export JAVA_HOME to PATH
  lineinfile:
    path: '{{ sys_profile }}'
    line: 'export PATH=$PATH:$JAVA_HOME/bin'
