---

- name: download and unzip
  include_role:
    name: basic/download_and_unzip
  vars:
    pkg_conf: '{{ pkg_ic }}'

# export environment variable
- name: export JAVA_HOME (/etc/environment)
  lineinfile:
    path: /etc/environment
    regexp: '^JAVA_HOME='
    line: 'JAVA_HOME={{ pkg_ic.install_path }}/{{ pkg_ic.basename }}'
- name: export JAVA_HOME
  lineinfile:
    path: "{{ sys_profile }}"
    regexp: '^export JAVA_HOME='
    line: 'export JAVA_HOME={{ pkg_ic.install_path }}/{{ pkg_ic.basename }}'
- name: export JAVA_HOME to PATH
  lineinfile:
    path: '{{ sys_profile }}'
    line: 'export PATH=$PATH:$JAVA_HOME/bin'
