---

- name: fetch JAVA_HOME, setup if absent
  command: /bin/sh -l -c "echo $JAVA_HOME"
  register: fetch_java_home

# - name: show debug                          
#   debug: var=fetch_java_home

# - set_fact:
#     java_home_fact: "{{ fetch_java_home.stdout }}"

# - name: print JAVA_HOME
#   debug:
#     msg: "{{ java_home_fact}}"

- include: setup_jdk.yml
  when: "fetch_java_home.stdout == ''"