---

- include_vars: 
    file: '../../../vars/resources.yml'

- name: mkdir hadoop_conf_dir
  file: path="{{ role_path }}/files" state=directory

- name: check if jdk_tar_file exist
  stat: path="{{ role_path }}/files/{{ jdk_tar_filename }}"
  register: jdktarfstat

- name: download jdk
  get_url: url="{{ jdk_download_url }}" dest="{{ role_path }}/files/{{ jdk_tar_filename }}"
  when: not jdktarfstat.stat.exists

- name: check if hadoop_tar_file exist
  stat: path="{{ role_path }}/files/{{ hadoop_tar_filename }}"
  register: hadooptarfstat

- name: download hadoop
  get_url: url="{{ hadoop_download_url }}" dest="{{ role_path }}/files/{{ hadoop_tar_filename }}"
    checksum="{{ hadoop_download_checksum_sha256 }}"
  when: not hadooptarfstat.stat.exists

- name: check if sshkeys exist
  stat: path="{{ role_path }}/sshkeys"
  register: sskeystat

- name: mkdir sshkeys directory
  file: path="{{ role_path }}/sshkeys" state=directory

- name: generate ssh keys
  shell: ssh-keygen -t rsa -P '' -f {{ role_path }}/sshkeys/{{ item}}_rsa -C {{ item }}@hadoop-cluster
  with_items:
    - hadoop
    - hdfs
    - yarn
    - mapred
  when: sskeystat.stat.isdir is not defined
