---

- include_vars: 
    file: '../../../vars/resources.yml'

- name: ensure hadoop_conf_dir dir
  file: path="{{ role_path }}/files" state=directory

- name: check if jdk_tar_file exist
  stat: path="{{ role_path }}/files/{{ jdk_tar_filename }}"
  register: jdktarfstat

- name: Download jdk
  get_url: url="{{ jdk_download_url }}" dest="{{ role_path }}/files/{{ jdk_tar_file_name }}"
  when: not jdktarfstat.stat.exists

- name: check if jdk_tar_file exist
  stat: path="{{ role_path }}/files/{{ hadoop_tar_filename }}"
  register: hadooptarfstat

- name: Download hadoop
  get_url: url="{{ hadoop_download_url }}" dest="{{ role_path }}/files/{{ hadoop_tar_filename }}"
    checksum="{{ hadoop_download_checksum_sha256 }}"
  when: not hadooptarfstat.stat.exists

